name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get changed typescript files
        id: changed-typescript-files
        uses: tj-actions/changed-files@v20
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          files: |
            **/*.ts
            **/*.tsx

      - name: TypeScript report
        if: steps.changed-typescript-files.outputs.any_changed == 'true'
        uses: fersilva16/ts-report-action@1.1.0
        with:
          files: ${{ steps.changed-typescript-files.outputs.all_changed_files }}
# name: Check code

# on: [push]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Run linter
#         uses: actionsx/prettier@v2

#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: Apply Prettier
#           skip_fetch: true
