name: Test

on: [pull_request]

jobs:
  test:
    name: Typescript Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint

      # - name: Typecheck
      #   uses: andoshin11/typescript-error-reporter-action@v1.0.2

      - name: tsc
        uses: icrawl/action-tsc@v1
# name: Check code

# on: [push]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Run linter
#         uses: actionsx/prettier@v2

#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: Apply Prettier
#           skip_fetch: true
