name: Test

on: [pull_request]

jobs:
  test:
    name: Typescript Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        run: yarn lint
# name: Check code

# on: [push]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Run linter
#         uses: actionsx/prettier@v2

#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: Apply Prettier
#           skip_fetch: true
